//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.Web.BookShop {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtTitle;
		protected global::System.Web.UI.WebControls.TextBox txtTitleHot;
		protected global::System.Web.UI.WebControls.TextBox txtPriceOld;
		protected global::System.Web.UI.WebControls.TextBox txtPriceNew;
		protected global::System.Web.UI.WebControls.TextBox txtAuthor;
		protected global::System.Web.UI.WebControls.TextBox txtPublisher;
		protected global::System.Web.UI.WebControls.TextBox txtPublishDate;
		protected global::System.Web.UI.WebControls.TextBox txtOnSaleDate;
		protected global::System.Web.UI.WebControls.TextBox txtISBN;
		protected global::System.Web.UI.WebControls.TextBox txtTypeId;
		protected global::System.Web.UI.WebControls.TextBox txtDetails;
		protected global::System.Web.UI.WebControls.TextBox txtImgTitle;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
