//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop.Web.BookShop {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblBid;
	protected global::System.Web.UI.WebControls.Label lblTitle;
	protected global::System.Web.UI.WebControls.Label lblTitleHot;
	protected global::System.Web.UI.WebControls.Label lblPriceOld;
	protected global::System.Web.UI.WebControls.Label lblPriceNew;
	protected global::System.Web.UI.WebControls.Label lblAuthor;
	protected global::System.Web.UI.WebControls.Label lblPublisher;
	protected global::System.Web.UI.WebControls.Label lblPublishDate;
	protected global::System.Web.UI.WebControls.Label lblOnSaleDate;
	protected global::System.Web.UI.WebControls.Label lblISBN;
	protected global::System.Web.UI.WebControls.Label lblTypeId;
	protected global::System.Web.UI.WebControls.Label lblDetails;
	protected global::System.Web.UI.WebControls.Label lblImgTitle;


       
    }
}
